# Generated by Django 4.1.1 on 2022-10-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('ex', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('c_like', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to='yorizori_app.memberinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='yorizori_app.memberinfo')),
                ('report', models.CharField(blank=True, max_length=100, null=True)),
                ('c_report', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('coment', models.CharField(blank=True, max_length=100, null=True)),
                ('num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yorizori_app.memberinfo')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='yorizori_app.recipe')),
            ],
        ),
    ]
